"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useSearchParams } from "next/navigation";
import { getSupabaseBrowserClient, supabaseConfigured } from "@/lib/supabase-browser";
import { DEFAULT_COUNTRY_CODE, ENABLED_COUNTRIES } from "@/lib/countries";

export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const signup = mode === "signup"; const searchParams = useSearchParams(); const [email, setEmail] = useState(""); const [countryCode, setCountryCode] = useState(DEFAULT_COUNTRY_CODE); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const requestedNext = searchParams.get("next"); const destination = requestedNext?.startsWith("/") && !requestedNext.startsWith("//") ? requestedNext : "/";
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); const normalizedEmail = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) { setError("Enter a valid email address."); return; } const supabase = getSupabaseBrowserClient(); if (!supabaseConfigured() || !supabase) { setError("Authentication has not been configured yet."); return; } setLoading(true); const { error: magicLinkError } = await supabase.auth.signInWithOtp({ email: normalizedEmail, options: { shouldCreateUser: signup, emailRedirectTo: `${window.location.origin}/auth/callback?next=${encodeURIComponent(destination)}`, ...(signup ? { data: { country_code: countryCode } } : {}) } }); setLoading(false); if (magicLinkError) { setError(/rate limit/i.test(magicLinkError.message) ? "Please wait before requesting another link." : signup ? "We could not send the sign-up link. Please try again." : "We could not send a sign-in link. Use the email you registered with."); return; } setMessage(`We sent a secure link to ${normalizedEmail}. Open it in this browser to continue.`); }
  return <main className="auth-page shell"><section className="auth-card"><p className="eyebrow">Project Y account</p><h1>{signup ? "Create your account" : "Welcome back"}</h1><p>{signup ? "Enter your email and country. Your account is ready when you open the secure link." : "Enter the email you used to create your account and we’ll send a secure sign-in link."}</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required autoFocus /></label>{signup ? <label>Country<select value={countryCode} onChange={(event) => setCountryCode(event.target.value)} autoComplete="country">{ENABLED_COUNTRIES.map((country) => <option key={country.code} value={country.code}>{country.flag} {country.name}</option>)}</select></label> : null}{error ? <p className="form-error" role="alert">{error}</p> : null}{message ? <p className="form-message" role="status">{message}</p> : null}<button className="primary-link" disabled={loading}>{loading ? "Sending…" : signup ? "Send sign-up link" : "Send sign-in link"}</button></form><p className="auth-switch">{signup ? "Already have an account?" : "New to Project Y?"} <Link href={`${signup ? "/login" : "/signup"}?next=${encodeURIComponent(destination)}`}>{signup ? "Sign in" : "Create one"}</Link></p></section></main>;
}
