"use client";
import { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { COUNTRY_PREFERENCE_COOKIE, COUNTRY_PREFERENCE_STORAGE_KEY, DEFAULT_COUNTRY_CODE, getCountry, isEnabledCountryCode, type Country } from "@/lib/countries";
import { useAuth } from "@/components/auth-provider";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
type CountryValue = { country: Country; accountCountry: Country | null; setCountry: (code: string) => void; loading: boolean };
const CountryContext = createContext<CountryValue | null>(null);
function savedCountry(){if(typeof window==="undefined")return DEFAULT_COUNTRY_CODE;const saved=window.localStorage.getItem(COUNTRY_PREFERENCE_STORAGE_KEY);return isEnabledCountryCode(saved)?saved.toUpperCase():DEFAULT_COUNTRY_CODE;}
function metadataCountry(user:{user_metadata:Record<string,unknown>}){const code=user.user_metadata.country_code;return typeof code==="string"&&isEnabledCountryCode(code)?code.toUpperCase():DEFAULT_COUNTRY_CODE;}
export function CountryProvider({children}:{children:React.ReactNode}){const {user,loading:authLoading}=useAuth();const router=useRouter();const [countryCode,setCountryCode]=useState(savedCountry);const [accountCountryCode,setAccountCountryCode]=useState<string|null>(null);const [loading,setLoading]=useState(true);const hasSavedPreference=useRef(typeof window!=="undefined"&&Boolean(window.localStorage.getItem(COUNTRY_PREFERENCE_STORAGE_KEY)));function persist(code:string){window.localStorage.setItem(COUNTRY_PREFERENCE_STORAGE_KEY,code);document.cookie=`${COUNTRY_PREFERENCE_COOKIE}=${code}; Path=/; Max-Age=31536000; SameSite=Lax`; }function setCountry(code:string){if(!isEnabledCountryCode(code))return;const next=code.toUpperCase();setCountryCode(next);persist(next);router.refresh();}useEffect(()=>{persist(countryCode);setLoading(false);},[]);useEffect(()=>{if(authLoading)return;if(!user){setAccountCountryCode(null);return;}const supabase=getSupabaseBrowserClient();if(!supabase)return;let active=true;const fallback=metadataCountry(user);supabase.from("profiles").select("country_code").eq("user_id",user.id).maybeSingle().then(async({data,error})=>{if(!active)return;const code=!error&&data&&isEnabledCountryCode(data.country_code)?data.country_code.toUpperCase():fallback;if(error||!data)await supabase.from("profiles").upsert({user_id:user.id,name:typeof user.user_metadata.full_name==="string"?user.user_metadata.full_name:null,country_code:code},{onConflict:"user_id"});if(!active)return;setAccountCountryCode(code);if(!hasSavedPreference.current){setCountryCode(code);persist(code);router.refresh();}});return()=>{active=false;};},[authLoading,user,router]);const value=useMemo(()=>({country:getCountry(countryCode),accountCountry:accountCountryCode?getCountry(accountCountryCode):null,setCountry,loading}),[countryCode,accountCountryCode,loading]);return <CountryContext.Provider value={value}>{children}</CountryContext.Provider>;}
export function useCountry(){const value=useContext(CountryContext);if(!value)throw new Error("useCountry must be used inside CountryProvider");return value;}
