"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import { imageUrl, type MediaType, type WatchProviders } from "@/lib/media";
import { TitleWishlistAction } from "@/components/title-wishlist-action";
import { useCountry } from "@/components/country-provider";
type Props = { mediaType: MediaType; titleId: number; initialProviders: WatchProviders; initialRegion: string };
// A router refresh can supersede the client fetch; clear its loading state when server props catch up.
export function WatchProviders({mediaType,titleId,initialProviders,initialRegion}:Props){const {country}=useCountry();const [providers,setProviders]=useState(initialProviders),[loading,setLoading]=useState(false),[error,setError]=useState("");useEffect(()=>{setProviders(initialProviders);},[initialProviders,initialRegion]);useEffect(()=>{if(country.code===initialRegion){setLoading(false);setError("");return;}let active=true;setLoading(true);setError("");fetch(`/api/title/${mediaType}/${titleId}/providers?region=${country.tmdbRegion}`,{cache:"no-store"}).then(async response=>{const payload=await response.json() as {providers?:WatchProviders;error?:string};if(!response.ok||!payload.providers)throw new Error(payload.error);if(active)setProviders(payload.providers);}).catch(()=>{if(active)setError("Provider availability is temporarily unavailable. Please try again.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[country.code,country.tmdbRegion,initialRegion,mediaType,titleId]);const groups=[["Stream",providers.flatrate],["Rent",providers.rent],["Buy",providers.buy],["Free / ads",[...providers.free,...providers.ads]]] as const;const hasProviders=groups.some(([,items])=>items.length>0);return <><TitleWishlistAction mediaType={mediaType} titleId={titleId}/><section className="detail-section" aria-labelledby="watch-title"><div className="detail-section-heading"><div><p className="eyebrow">Availability · {country.flag} {country.name}</p><h2 id="watch-title">Where to watch in {country.name}</h2></div></div>{loading?<p className="section-status">Checking availability in {country.name}…</p>:error?<p className="section-status">{error}</p>:hasProviders?<div className="provider-groups">{groups.map(([label,items])=>items.length?<div key={label} className="provider-group"><h3>{label}</h3><div>{items.map(provider=><span className="provider" key={`${label}-${provider.id}`}>{provider.logoPath?<Image src={imageUrl(provider.logoPath,"w92")!} alt="" width={30} height={30}/>:null}<span>{provider.name}</span></span>)}</div></div>:null)}</div>:<p className="section-status">No provider availability is reported for {country.name} right now.</p>}{providers.link?<a className="provider-link" href={providers.link} target="_blank" rel="noreferrer">View availability details on TMDB ↗</a>:null}</section></>;}
