export type Country = { code: string; name: string; flag: string; tmdbRegion: string; locale: string; enabled: boolean };
export const DEFAULT_COUNTRY_CODE = "IN";
export const COUNTRY_PREFERENCE_COOKIE = "ifynex_country";
export const COUNTRY_PREFERENCE_STORAGE_KEY = "ifynex.current-country";
export const COUNTRIES: readonly Country[] = [
  {code:"IN",name:"India",flag:"🇮🇳",tmdbRegion:"IN",locale:"en-IN",enabled:true},{code:"US",name:"United States",flag:"🇺🇸",tmdbRegion:"US",locale:"en-US",enabled:true},{code:"GB",name:"United Kingdom",flag:"🇬🇧",tmdbRegion:"GB",locale:"en-GB",enabled:true},{code:"CA",name:"Canada",flag:"🇨🇦",tmdbRegion:"CA",locale:"en-CA",enabled:true},{code:"AU",name:"Australia",flag:"🇦🇺",tmdbRegion:"AU",locale:"en-AU",enabled:true},{code:"DE",name:"Germany",flag:"🇩🇪",tmdbRegion:"DE",locale:"de-DE",enabled:true},{code:"FR",name:"France",flag:"🇫🇷",tmdbRegion:"FR",locale:"fr-FR",enabled:true},{code:"ES",name:"Spain",flag:"🇪🇸",tmdbRegion:"ES",locale:"es-ES",enabled:true},{code:"IT",name:"Italy",flag:"🇮🇹",tmdbRegion:"IT",locale:"it-IT",enabled:true},{code:"NL",name:"Netherlands",flag:"🇳🇱",tmdbRegion:"NL",locale:"nl-NL",enabled:true},{code:"SE",name:"Sweden",flag:"🇸🇪",tmdbRegion:"SE",locale:"sv-SE",enabled:true},{code:"NO",name:"Norway",flag:"🇳🇴",tmdbRegion:"NO",locale:"nb-NO",enabled:true},{code:"DK",name:"Denmark",flag:"🇩🇰",tmdbRegion:"DK",locale:"da-DK",enabled:true},{code:"FI",name:"Finland",flag:"🇫🇮",tmdbRegion:"FI",locale:"fi-FI",enabled:true},{code:"PL",name:"Poland",flag:"🇵🇱",tmdbRegion:"PL",locale:"pl-PL",enabled:true},{code:"BR",name:"Brazil",flag:"🇧🇷",tmdbRegion:"BR",locale:"pt-BR",enabled:true},{code:"MX",name:"Mexico",flag:"🇲🇽",tmdbRegion:"MX",locale:"es-MX",enabled:true},{code:"JP",name:"Japan",flag:"🇯🇵",tmdbRegion:"JP",locale:"ja-JP",enabled:true},{code:"KR",name:"South Korea",flag:"🇰🇷",tmdbRegion:"KR",locale:"ko-KR",enabled:true},{code:"SG",name:"Singapore",flag:"🇸🇬",tmdbRegion:"SG",locale:"en-SG",enabled:true},{code:"AE",name:"United Arab Emirates",flag:"🇦🇪",tmdbRegion:"AE",locale:"ar-AE",enabled:true},{code:"SA",name:"Saudi Arabia",flag:"🇸🇦",tmdbRegion:"SA",locale:"ar-SA",enabled:true},{code:"NZ",name:"New Zealand",flag:"🇳🇿",tmdbRegion:"NZ",locale:"en-NZ",enabled:true}
];
export const ENABLED_COUNTRIES = COUNTRIES.filter((country) => country.enabled);
export function getCountry(code?: string | null): Country { return COUNTRIES.find((country) => country.code === code?.toUpperCase() && country.enabled) ?? COUNTRIES.find((country) => country.code === DEFAULT_COUNTRY_CODE)!; }
export function isEnabledCountryCode(code?: string | null): code is string { return Boolean(code && ENABLED_COUNTRIES.some((country) => country.code === code.toUpperCase())); }
