import "server-only";

export type MediaType = "movie" | "tv";
export type Media = { id:number; mediaType:MediaType; title:string; overview:string; posterPath?:string; backdropPath?:string; releaseDate?:string; rating:number; voteCount:number; genreIds:number[] };
export type TmdbResult<T> = { data:T; error?:never } | { data?:never; error:"not-configured"|"not-found"|"unauthorized"|"upstream" };
const API = "https://api.themoviedb.org/3";
const key = () => process.env.TMDB_API_KEY?.trim();
const REQUEST_TIMEOUT_MS = 10_000;
const successfulCollections = new Map<string, Media[]>();
export const imageUrl = (path?: string, size = "w500") => path ? `https://image.tmdb.org/t/p/${size}${path}` : undefined;
type Diagnostic = { name:string; endpoint:string; success:boolean; status:number|null; durationMs:number; hasResults:boolean; resultCount:number; error?:"not-configured"|"timeout"|"network"|"invalid-response"|"http" };
function toMedia(raw: Record<string, unknown>, explicitType?: MediaType): Media { const mediaType=explicitType ?? (raw.media_type === "tv" ? "tv" : "movie"); return { id:Number(raw.id), mediaType, title:String(mediaType === "tv" ? raw.name ?? "Untitled series" : raw.title ?? "Untitled movie"), overview:String(raw.overview ?? ""), posterPath:typeof raw.poster_path === "string" ? raw.poster_path : undefined, backdropPath:typeof raw.backdrop_path === "string" ? raw.backdrop_path : undefined, releaseDate:String(mediaType === "tv" ? raw.first_air_date ?? "" : raw.release_date ?? "") || undefined, rating:Number(raw.vote_average ?? 0), voteCount:Number(raw.vote_count ?? 0), genreIds:Array.isArray(raw.genre_ids) ? raw.genre_ids.map(Number) : [] }; }
const wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function request<T>(path:string, params:Record<string,string> = {}):Promise<TmdbResult<T>> { const apiKey=key(); if(!apiKey)return{error:"not-configured"}; const url=new URL(`${API}${path}`); Object.entries({...params,api_key:apiKey,include_adult:"false"}).forEach(([name,value])=>url.searchParams.set(name,value)); for(let attempt=0;attempt<3;attempt+=1){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try { const response=await fetch(url,{next:{revalidate:1800},signal:controller.signal}); if(response.status===401||response.status===403)return{error:"unauthorized"}; if(response.status===404)return{error:"not-found"}; if(response.ok){const json=await response.json();if(json&&typeof json==="object")return{data:json as T};} if(response.status<500&&response.status!==429)return{error:"upstream"}; } catch { /* Retry transient network failures and timeouts. */ } finally { clearTimeout(timeout); } if(attempt<2)await wait(350*(attempt+1)); } return{error:"upstream"}; }
export async function getCollection(type:MediaType, collection:"popular"|"top_rated"|"trending"):Promise<TmdbResult<Media[]>> { const cacheKey=`${type}:${collection}`; const path=collection === "trending" ? `/trending/${type}/week` : `/${type}/${collection}`; const result=await request<{results?:Record<string,unknown>[] }>(path,{language:"en-US"}); if("data"in result && result.data){const mapped=Array.isArray(result.data.results)?result.data.results.map(item=>toMedia(item,type)):[];if(mapped.length)successfulCollections.set(cacheKey,mapped);return{data:mapped};} const lastSuccess=successfulCollections.get(cacheKey); return lastSuccess?{data:lastSuccess}:result; }
export async function searchMedia(query:string):Promise<TmdbResult<Media[]>> { const cleaned=query.trim(); if(!cleaned)return{data:[]}; const result=await request<{results?:Record<string,unknown>[] }>("/search/multi",{query:cleaned,language:"en-US"}); if("data"in result&&result.data)return{data:(result.data.results??[]).filter(item=>item.media_type==="movie"||item.media_type==="tv").map(item=>toMedia(item))}; return result; }
export async function diagnoseCollections():Promise<Diagnostic[]>{const targets=[{name:"Trending Movies",endpoint:"/trending/movie/week"},{name:"Popular Movies",endpoint:"/movie/popular"},{name:"Top Rated Movies",endpoint:"/movie/top_rated"},{name:"Popular TV Shows",endpoint:"/tv/popular"},{name:"Trending TV Shows",endpoint:"/trending/tv/week"}];const apiKey=key();if(!apiKey)return targets.map(target=>({...target,success:false,status:null,durationMs:0,hasResults:false,resultCount:0,error:"not-configured" as const}));return Promise.all(targets.map(async target=>{const started=Date.now(),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);const url=new URL(`${API}${target.endpoint}`);url.searchParams.set("api_key",apiKey);url.searchParams.set("language","en-US");try{const response=await fetch(url,{cache:"no-store",signal:controller.signal});const durationMs=Date.now()-started;if(!response.ok)return{...target,success:false,status:response.status,durationMs,hasResults:false,resultCount:0,error:"http" as const};const body=await response.json() as {results?:unknown};const count=Array.isArray(body?.results)?body.results.length:0;return{...target,success:true,status:response.status,durationMs,hasResults:count>0,resultCount:count};}catch(error){const durationMs=Date.now()-started;return{...target,success:false,status:null,durationMs,hasResults:false,resultCount:0,error:(error instanceof DOMException&&error.name==="AbortError"?"timeout":"network") as "timeout"|"network"};}finally{clearTimeout(timeout);}}));}
