import "server-only";
import { type Media, type MediaType, type Provider, type WatchProviders } from "@/lib/media";

export { imageUrl, type Media, type MediaType, type Provider, type WatchProviders } from "@/lib/media";

export type TmdbResult<T> = { data:T; error?:never } | { data?:never; error:"not-configured"|"not-found"|"unauthorized"|"upstream" };
export type Person = { id:number; name:string; role:string; profilePath?:string };
export type Video = { id:string; name:string; key:string; site:"YouTube"; type:string; official:boolean };
export type Review = { id:string; author:string; content:string; createdAt?:string; url?:string };
export type TitleDetails = Media & { originalTitle?:string; tagline?:string; runtime?:number; genres:string[]; originalLanguage?:string; countries:string[]; companies:string[]; status?:string; budget?:number; revenue?:number; imdbId?:string; cast:Person[]; crew:Person[]; videos:Video[]; recommendations:Media[]; similar:Media[]; reviews:Review[] };
const API = "https://api.themoviedb.org/3";
const key = () => process.env.TMDB_API_KEY?.trim();
const REQUEST_TIMEOUT_MS = 10_000;
const successfulCollections = new Map<string, Media[]>();
type Diagnostic = { name:string; endpoint:string; success:boolean; status:number|null; durationMs:number; hasResults:boolean; resultCount:number; error?:"not-configured"|"timeout"|"network"|"invalid-response"|"http" };
function toMedia(raw: Record<string, unknown>, explicitType?: MediaType): Media { const mediaType=explicitType ?? (raw.media_type === "tv" ? "tv" : "movie"); return { id:Number(raw.id), mediaType, title:String(mediaType === "tv" ? raw.name ?? "Untitled series" : raw.title ?? "Untitled movie"), overview:String(raw.overview ?? ""), posterPath:typeof raw.poster_path === "string" ? raw.poster_path : undefined, backdropPath:typeof raw.backdrop_path === "string" ? raw.backdrop_path : undefined, releaseDate:String(mediaType === "tv" ? raw.first_air_date ?? "" : raw.release_date ?? "") || undefined, rating:Number(raw.vote_average ?? 0), voteCount:Number(raw.vote_count ?? 0), genreIds:Array.isArray(raw.genre_ids) ? raw.genre_ids.map(Number) : [] }; }
const wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function request<T>(path:string, params:Record<string,string> = {}):Promise<TmdbResult<T>> { const apiKey=key(); if(!apiKey)return{error:"not-configured"}; const url=new URL(`${API}${path}`); Object.entries({...params,api_key:apiKey,include_adult:"false"}).forEach(([name,value])=>url.searchParams.set(name,value)); for(let attempt=0;attempt<3;attempt+=1){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try { const response=await fetch(url,{next:{revalidate:1800},signal:controller.signal}); if(response.status===401||response.status===403)return{error:"unauthorized"}; if(response.status===404)return{error:"not-found"}; if(response.ok){const json=await response.json();if(json&&typeof json==="object")return{data:json as T};} if(response.status<500&&response.status!==429)return{error:"upstream"}; } catch { /* Retry transient network failures and timeouts. */ } finally { clearTimeout(timeout); } if(attempt<2)await wait(350*(attempt+1)); } return{error:"upstream"}; }
export async function getCollection(type:MediaType, collection:"popular"|"top_rated"|"trending", region?:string):Promise<TmdbResult<Media[]>> { const normalizedRegion=/^[A-Z]{2}$/.test(region?.toUpperCase() ?? "") ? region!.toUpperCase() : undefined; const supportsRegion=type === "movie" && collection === "popular"; const cacheKey=`${type}:${collection}:${supportsRegion ? normalizedRegion ?? "global" : "global"}`; const path=collection === "trending" ? `/trending/${type}/week` : `/${type}/${collection}`; const result=await request<{results?:Record<string,unknown>[] }>(path,{language:"en-US",...(supportsRegion&&normalizedRegion?{region:normalizedRegion}:{})}); if("data"in result && result.data){const mapped=Array.isArray(result.data.results)?result.data.results.map(item=>toMedia(item,type)):[];if(mapped.length)successfulCollections.set(cacheKey,mapped);return{data:mapped};} const lastSuccess=successfulCollections.get(cacheKey); return lastSuccess?{data:lastSuccess}:result; }
function discoverItems(result:TmdbResult<{results?:Record<string,unknown>[] }>, type:MediaType):Media[] { return "data"in result&&result.data&&Array.isArray(result.data.results)?result.data.results.map(item=>toMedia(item,type)):[]; }
function alternateMedia(movies:Media[], tv:Media[]):Media[] { const result:Media[]=[]; for(let index=0;index<Math.max(movies.length,tv.length);index+=1){if(movies[index])result.push(movies[index]);if(tv[index])result.push(tv[index]);} return result; }
function balanceCountryAvailability(globalItems:Media[], localItems:Media[], limit=18):Media[] { const result:Media[]=[]; const seen=new Set<string>(); let globalIndex=0,localIndex=0; const add=(item:Media|undefined)=>{if(!item||result.length>=limit)return false;const key=`${item.mediaType}-${item.id}`;if(seen.has(key))return false;seen.add(key);result.push(item);return true;}; while(result.length<limit&&(globalIndex<globalItems.length||localIndex<localItems.length)){let progressed=false;for(let count=0;count<2&&globalIndex<globalItems.length;count+=1)progressed=add(globalItems[globalIndex++])||progressed;if(localIndex<localItems.length)progressed=add(localItems[localIndex++])||progressed;if(!progressed&&globalIndex>=globalItems.length&&localIndex>=localItems.length)break;} return result; }
export async function getPopularAvailableInRegion(region:string):Promise<TmdbResult<Media[]>> { const normalizedRegion=region.toUpperCase(); if(!/^[A-Z]{2}$/.test(normalizedRegion))return{error:"not-found"}; const cacheKey=`available-balanced:${normalizedRegion}`; const availability={language:"en-US",watch_region:normalizedRegion,with_watch_monetization_types:"flatrate|free|ads|rent|buy",sort_by:"popularity.desc","vote_count.gte":"25"}; const localAvailability={...availability,with_origin_country:normalizedRegion}; const [globalMovies,globalTV,localMovies,localTV]=await Promise.all([request<{results?:Record<string,unknown>[] }>("/discover/movie",availability),request<{results?:Record<string,unknown>[] }>("/discover/tv",availability),request<{results?:Record<string,unknown>[] }>("/discover/movie",localAvailability),request<{results?:Record<string,unknown>[] }>("/discover/tv",localAvailability)]); const globalItems=alternateMedia(discoverItems(globalMovies,"movie"),discoverItems(globalTV,"tv")); const localItems=alternateMedia(discoverItems(localMovies,"movie"),discoverItems(localTV,"tv")); const merged=balanceCountryAvailability(globalItems,localItems); if(merged.length){successfulCollections.set(cacheKey,merged);return{data:merged};} const lastSuccess=successfulCollections.get(cacheKey); if(lastSuccess)return{data:lastSuccess}; const upstreamError=("error"in globalMovies&&globalMovies.error)||("error"in globalTV&&globalTV.error)||("error"in localMovies&&localMovies.error)||("error"in localTV&&localTV.error)||"upstream"; return{error:upstreamError}; }
export async function searchMedia(query:string):Promise<TmdbResult<Media[]>> { const cleaned=query.trim(); if(!cleaned)return{data:[]}; const result=await request<{results?:Record<string,unknown>[] }>("/search/multi",{query:cleaned,language:"en-US"}); if("data"in result&&result.data)return{data:(result.data.results??[]).filter(item=>item.media_type==="movie"||item.media_type==="tv").map(item=>toMedia(item))}; return result; }
function list(raw:unknown):Record<string,unknown>[] { return Array.isArray(raw) ? raw.filter((item):item is Record<string,unknown> => Boolean(item) && typeof item === "object") : []; }
function namedList(raw:unknown):string[] { return Array.isArray(raw) ? raw.map(item => typeof item === "string" ? item : item && typeof item === "object" && typeof (item as Record<string,unknown>).name === "string" ? String((item as Record<string,unknown>).name) : "").filter(Boolean) : []; }
function providerList(raw:unknown):Provider[] { return list(raw).map(item => ({ id:Number(item.provider_id), name:String(item.provider_name ?? "Provider"), logoPath:typeof item.logo_path === "string" ? item.logo_path : undefined })).filter(item => Number.isFinite(item.id)); }
function normalizeDetails(raw:Record<string,unknown>, type:MediaType):TitleDetails { const media=toMedia(raw,type); const credits=(raw.credits && typeof raw.credits === "object" ? raw.credits : {}) as Record<string,unknown>; const videos=(raw.videos && typeof raw.videos === "object" ? raw.videos : {}) as Record<string,unknown>; const recommendations=(raw.recommendations && typeof raw.recommendations === "object" ? raw.recommendations : {}) as Record<string,unknown>; const similar=(raw.similar && typeof raw.similar === "object" ? raw.similar : {}) as Record<string,unknown>; const reviews=(raw.reviews && typeof raw.reviews === "object" ? raw.reviews : {}) as Record<string,unknown>; const people=(items:unknown, roleKey:"character"|"job") => list(items).slice(0,14).map(item => ({id:Number(item.id),name:String(item.name ?? "Unknown"),role:String(item[roleKey] ?? ""),profilePath:typeof item.profile_path === "string" ? item.profile_path : undefined})).filter(item=>Number.isFinite(item.id)); const crew=people(credits.crew,"job").filter(person=>["Director","Writer","Screenplay","Producer","Executive Producer","Creator"].includes(person.role)).slice(0,8); return {...media, originalTitle:typeof (type === "tv" ? raw.original_name : raw.original_title) === "string" ? String(type === "tv" ? raw.original_name : raw.original_title) : undefined, tagline:typeof raw.tagline === "string" ? raw.tagline : undefined, runtime:Number(type === "tv" ? list(raw.episode_run_time)[0] : raw.runtime) || undefined, genres:namedList(raw.genres), originalLanguage:typeof raw.original_language === "string" ? raw.original_language.toUpperCase() : undefined, countries:namedList(type === "tv" ? raw.origin_country : raw.production_countries), companies:namedList(raw.production_companies), status:typeof raw.status === "string" ? raw.status : undefined, budget:Number(raw.budget) || undefined, revenue:Number(raw.revenue) || undefined, imdbId:typeof raw.imdb_id === "string" ? raw.imdb_id : undefined, cast:people(credits.cast,"character"), crew, videos:list(videos.results).filter(item=>item.site === "YouTube" && typeof item.key === "string").map(item=>({id:String(item.id),name:String(item.name ?? "Video"),key:String(item.key),site:"YouTube" as const,type:String(item.type ?? "Video"),official:item.official === true})).slice(0,8), recommendations:list(recommendations.results).map(item=>toMedia(item,type)).slice(0,12), similar:list(similar.results).map(item=>toMedia(item,type)).slice(0,12), reviews:list(reviews.results).slice(0,3).map(item=>({id:String(item.id),author:String(item.author ?? "TMDB member"),content:String(item.content ?? ""),createdAt:typeof item.created_at === "string" ? item.created_at : undefined,url:typeof item.url === "string" ? item.url : undefined}))}; }
export async function getTitleDetails(type:MediaType, id:number):Promise<TmdbResult<TitleDetails>> { if(!Number.isSafeInteger(id)||id<1)return{error:"not-found"}; const result=await request<Record<string,unknown>>(`/${type}/${id}`,{language:"en-US",append_to_response:"credits,videos,recommendations,similar,reviews,external_ids"}); return "data" in result && result.data ? {data:normalizeDetails(result.data,type)} : result; }
export async function getWatchProviders(type:MediaType, id:number, region:string):Promise<TmdbResult<WatchProviders>> { if(!Number.isSafeInteger(id)||id<1)return{error:"not-found"}; const normalizedRegion=region.toUpperCase(); if(!/^[A-Z]{2}$/.test(normalizedRegion))return{error:"not-found"}; const result=await request<Record<string,unknown>>(`/${type}/${id}/watch/providers`); if(!("data" in result) || !result.data)return result; const allResults=result.data.results; const item=allResults && typeof allResults === "object" ? (allResults as Record<string,unknown>)[normalizedRegion] : undefined; if(!item || typeof item !== "object")return{data:{flatrate:[],rent:[],buy:[],free:[],ads:[]}}; const values=item as Record<string,unknown>; return{data:{link:typeof values.link === "string" ? values.link : undefined,flatrate:providerList(values.flatrate),rent:providerList(values.rent),buy:providerList(values.buy),free:providerList(values.free),ads:providerList(values.ads)}}; }
export async function diagnoseCollections():Promise<Diagnostic[]>{const targets=[{name:"Trending Movies",endpoint:"/trending/movie/week"},{name:"Popular Movies",endpoint:"/movie/popular"},{name:"Top Rated Movies",endpoint:"/movie/top_rated"},{name:"Popular TV Shows",endpoint:"/tv/popular"},{name:"Trending TV Shows",endpoint:"/trending/tv/week"}];const apiKey=key();if(!apiKey)return targets.map(target=>({...target,success:false,status:null,durationMs:0,hasResults:false,resultCount:0,error:"not-configured" as const}));return Promise.all(targets.map(async target=>{const started=Date.now(),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);const url=new URL(`${API}${target.endpoint}`);url.searchParams.set("api_key",apiKey);url.searchParams.set("language","en-US");try{const response=await fetch(url,{cache:"no-store",signal:controller.signal});const durationMs=Date.now()-started;if(!response.ok)return{...target,success:false,status:response.status,durationMs,hasResults:false,resultCount:0,error:"http" as const};const body=await response.json() as {results?:unknown};const count=Array.isArray(body?.results)?body.results.length:0;return{...target,success:true,status:response.status,durationMs,hasResults:count>0,resultCount:count};}catch(error){const durationMs=Date.now()-started;return{...target,success:false,status:null,durationMs,hasResults:false,resultCount:0,error:(error instanceof DOMException&&error.name==="AbortError"?"timeout":"network") as "timeout"|"network"};}finally{clearTimeout(timeout);}}));}
